const data = {
    products: [
      {
        name: 'Hyderabadi biryani',
        category: 'Biryani',
        image: '/images/biryani1.jpeg' ,
        price: 300,
        countInStock: 10,
        hotel: 'Sai surya restuarant',
        rating: 9,
        numReviews: 10,
        description: 'Hyderabadi biryani is a flavorful and aromatic rice dish made with basmati rice, tender marinated meat, and a blend of spices, traditionally cooked in a dum style.',
      },
      {
        name: 'Chicken manchuria',
        category: 'Staters',
        image: '/images/manchuria1.jpeg',
        price: 250,
        countInStock: 0,
        hotel: 'chillies',
        rating: 8,
        numReviews: 10,
        description: 'Chicken Manchuria is a popular Indo-Chinese dish featuring crispy fried chicken pieces tossed in a tangy and spicy sauce with garlic, soy, and chili flavors.',
      },
      {
        name: 'dark forest',
        category: 'cake',
        image: '/images/cake1.jpeg',
        price: 500,
        countInStock: 15,
        hotel: 'Mufti bakery',
        rating: 9,
        numReviews: 14,
        description: 'Dark Forest is a decadent chocolate cake layered with rich chocolate ganache, sweet cherries, and whipped cream, inspired by the classic Black Forest gâteau.',
      },
      {
        name: 'strips',
        category: 'KFC',
        image: '/images/strips1.jpeg',
        price: 300,
        countInStock: 5,
        hotel: 'kfc',
        rating: 9,
        numReviews: 10,
        description: 'KFC chicken strips are tender, boneless pieces of chicken, seasoned with the Colonels secret blend of herbs and spices, and fried to crispy perfection.',
      },
      {
        name: 'Dry fruit milkshake',
        category: 'milk',
        image: '/images/milk1.jpeg',
        price: 150,
        countInStock: 5,
        hotel: 'sai ram juices',
        rating: 7,
        numReviews: 10,
        description: 'Dry fruit milkshake is a creamy and nutritious beverage made by blending milk with a mix of dried fruits such as almonds, cashews, dates, and raisins, often flavored with cardamom or saffron.',
      },
      {
        name: 'Pizza',
        category: 'snack',
        image: '/images/pizza1.jpeg',
        price: 400,
        countInStock: 5,
        hotel: 'dommino',
        rating: 8,
        numReviews: 10,
        description: 'Pizza is a beloved Italian dish featuring a thin or thick crust topped with tomato sauce, cheese, and a variety of toppings, baked to perfection.',
      },
      {
        name: 'Chicken soup',
        category: 'soup',
        image: '/images/soup1.jpeg',
        price: 250,
        countInStock: 5,
        hotel: 'Rama restuarant',
        rating: 7,
        numReviews: 10,
        description: 'Chicken soup is a comforting and nourishing dish made by simmering chicken with vegetables, herbs, and spices, often served as a warm, flavorful broth.',
      },
      {
        name: 'Butter naan',
        category: 'staters',
        image: '/images/staters1.jpeg',
        price: 300,
        countInStock: 5,
        hotel: 'Gopi restuarant',
        rating: 9,
        numReviews: 10,
        description: 'Butter naan is a soft and fluffy Indian flatbread made from refined flour, cooked in a tandoor, and generously brushed with butter for a rich flavor.',
      },
  
      {
        name: 'berry milk shake ',
        category: 'juice',
        image: '/images/juice1.jpeg',
        price: 30,
        countInStock: 5,
        hotel: 'sitara',
        rating: 7,
        numReviews: 10,
        description: 'Berry milkshake is a refreshing and fruity beverage made by blending milk with a mix of berries like strawberries, blueberries, and raspberries, often sweetened and served chilled.',
      },
    ],
  };
  export default data;